name: dart_seq
description: A Dart logging client for (batched) Seq HTTP ingestion with automated retries.
version: 3.0.0
homepage: https://github.com/ricardoboss/dart_seq
issue_tracker: https://github.com/ricardoboss/dart_seq/issues

topics:
  - logging
  - logger
  - seq
  - http
  - cache

screenshots:
  - ./doc/example_output.png

environment:
  sdk: ^3.8.0

dev_dependencies:
  strict: ^2.0.0
  test: ^1.25.2
