name: dart_seq
description: A Dart logging client for (batched) Seq HTTP ingestion with automated retries.
version: 0.0.2
homepage: https://github.com/ricardoboss/dart_seq

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  http: ^1.0.0
